Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2018-08, with the labels that each got.

#471 Move vm_reconnect spec to a correct location
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb
  spec/models/manager_refresh/inventory_collection_default_spec.rb
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_vm_reconnect.yml
Labels: test

#478 Move Inventory from ManagerRefresh to ManageIQ::Providers
  app/models/manageiq/providers/amazon/cloud_manager/refresher.rb
  app/models/manageiq/providers/amazon/inventory.rb
  app/models/manageiq/providers/amazon/inventory/collector.rb
  app/models/manageiq/providers/amazon/inventory/parser.rb
  app/models/manageiq/providers/amazon/inventory/persister.rb
Labels: refactoring

#481 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation
