Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2018-02, with the labels that each got.

#410 Fix refresh for stack without parameters
  app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/amazon/cloud_manager/specific_stubbed_refresher_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#409 Return created topic
  app/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream.rb
Labels: bug

#411 Raise Exception if AMI not visible
  app/models/manageiq/providers/amazon/agent_coordinator.rb
Labels: bug, gaprindashvili/yes, smart state

#412 Cleanup Smartstate Requests When AMI Unavailable for Agent
  app/models/manageiq/providers/amazon/agent_coordinator.rb
Labels: bug, gaprindashvili/yes, smart state

#413 Fix deprecated use of `have_attributes`
  spec/models/manageiq/providers/amazon/cloud_manager/orchestration_stack_spec.rb
Labels: technical debt, test

#408 [Changelog] Update for Sprint 79
  CHANGELOG.md
Labels: documentation

#414 test inventory reconnection
  spec/models/manager_refresh/inventory_collection_default_spec.rb
  spec/vcr_cassettes/manager_refresh/inventory_collection_default.yml
Labels: test

#416 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation
