Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2018-03, with the labels that each got.

#418 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#394 Tests cloud_networks with RBAC filtering from super
  spec/models/manageiq/providers/amazon/cloud_manager/provision_workflow_spec.rb
Labels: test

#415 Added instance update event handling
  config/settings.yml
Labels: bug, gaprindashvili/yes

#420 Updated flavors to include m5 instances
  app/models/manageiq/providers/amazon/instance_types.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
  spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
Labels: bug, fine/yes, gaprindashvili/yes

#423 [Changelog] Add Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#424 Fixes VPC selection to make sure it has internet gateway attached.
  app/models/manageiq/providers/amazon/agent_coordinator.rb
Labels: bug, gaprindashvili/yes, smart state

#425 Fix default filter for public images
  app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
  spec/models/manageiq/providers/amazon/cloud_manager/refresh_parser_spec.rb
Labels: bug, gaprindashvili/yes, inventory

#428 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation
