Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2018-11, with the labels that each got.

#497 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_Amazon.po
  locale/fr/ManageIQ_Providers_Amazon.po
  locale/ja/ManageIQ_Providers_Amazon.po
  locale/pt_BR/ManageIQ_Providers_Amazon.po
  locale/zh_CN/ManageIQ_Providers_Amazon.po
Labels: internationalization

#496 [HAMMER] [Changelog] Update for Hammer Beta2
  CHANGELOG.md
Labels: documentation

#498 Change saver_strategy value to String
  config/settings.yml
  spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
Labels: bug, gaprindashvili/yes, hammer/yes

#499 Service dialog for orchestration template no longer contains tenant selection
  spec/models/dialog/orchestration_template_amazon_service_dialog_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/orchestration_template_spec.rb
Labels: blocker, gaprindashvili/yes, hammer/yes

#501 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#502 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
