Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2018-09, with the labels that each got.

#483 Collect AWS service catalog items
  app/models/manageiq/providers/amazon/cloud_manager/service_instance.rb
  app/models/manageiq/providers/amazon/cloud_manager/service_offering.rb
  app/models/manageiq/providers/amazon/cloud_manager/service_parameters_set.rb
  app/models/manageiq/providers/amazon/inventory/collector.rb
  app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
  app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_inventory_object.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/ec2_classic_vm_and_lb_full_refresh.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stack.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested_with_vm.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_floating_ip_and_lbs_full_refresh.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_vm_reconnect.yml
Labels: enhancement

#482 avoid blank names by using uids
  app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
  app/models/manageiq/providers/amazon/inventory/parser.rb
  app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
  app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb
  app/models/manageiq/providers/amazon/parser_helper_methods.rb
  app/models/manageiq/providers/amazon/refresh_helper_methods.rb
  spec/models/manageiq/providers/amazon/cloud_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/amazon/network_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser_spec.rb
Labels: bug

#490 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
