Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2018-12, with the labels that each got.

#503 [Changelog] Update for Sprint 100
  CHANGELOG.md
Labels: documentation

#504 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes, test

#505 Change FactoryGirl to FactoryBot
  spec/factories/cloud_object_store.rb
  spec/factories/cloud_volume.rb
  spec/factories/cloud_volume_snapshot.rb
  spec/factories/ext_management_system.rb
  spec/factories/floating_ip.rb
  spec/factories/orchestration_template.rb
  spec/factories/service_parameters_set.rb
  spec/models/authenticator/amazon_spec.rb
  spec/models/dialog/orchestration_template_amazon_service_dialog_spec.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
  spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/orchestration_stack_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/orchestration_template_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/provision/configuration_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/provision_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/refresh_worker_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/specific_stubbed_refresher_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_other_region_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
  spec/models/manageiq/providers/amazon/network_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/amazon/network_manager/stubbed_refresher_spec.rb
  spec/models/manageiq/providers/amazon/network_manager_spec.rb
  spec/models/manageiq/providers/amazon/regions_spec.rb
  spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot_spec.rb
  spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_spec.rb
  spec/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser_spec.rb
  spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
  spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
  spec/tools/refresh_performance/aws_refresh_performance_cloud_manager.rb
  spec/tools/refresh_performance/aws_refresh_performance_network_manager.rb
Labels: dependencies, gaprindashvili/no, hammer/no

#506 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#508 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
