Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2018-06, with the labels that each got.

#450 [Changelog] Update for Sprint 86
  CHANGELOG.md
Labels: documentation

#451 [Changelog] Update for Sprint 87
  CHANGELOG.md
Labels: documentation

#452 Fix missing MiqServer in Authenticator spec
  spec/models/authenticator/amazon_spec.rb
Labels: test

#438 Persister: InventoryCollection building through add_collection()
  app/models/manageiq/providers/amazon/inventory/persister.rb
  app/models/manageiq/providers/amazon/inventory/persister/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/amazon/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/amazon/inventory/persister/definitions/storage_collections.rb
  app/models/manageiq/providers/amazon/inventory/persister/network_manager.rb
  app/models/manageiq/providers/amazon/inventory/persister/storage_manager/ebs.rb
  app/models/manageiq/providers/amazon/inventory/persister/storage_manager/s3.rb
  app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb
  app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory_collection_default/network_manager.rb
  app/models/manageiq/providers/amazon/inventory_collection_default/storage_manager.rb
Labels: refactoring

#439 handle volume snapshot status changes
  app/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream.rb
  app/models/manageiq/providers/amazon/cloud_manager/event_parser.rb
  app/models/manageiq/providers/amazon/cloud_manager/event_target_parser.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot.rb
  spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/config/EBS_Snapshot_Notification.json
  spec/models/manageiq/providers/amazon/cloud_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot_spec.rb
Labels: enhancement

#455 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation
