Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2019-10, with the labels that each got.

#562 Switch find_by_* to lookup_by_
  spec/models/authenticator/amazon_spec.rb
Labels: ivanchuk/no, refactoring

#565 Fix rspec expect taking a lambda as an argument
  spec/models/authenticator/amazon_spec.rb
Labels: test

#567 Remove zanata from README
  README.md
Labels: cleanup

#566 Remove zanata.xml
  zanata.xml
Labels: cleanup

#568 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: test
