Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2019-11, with the labels that each got.

#574 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#575 Remove checking for ems_ref_obj => nil
  spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Labels: cleanup

#576 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
  app/models/manageiq/providers/amazon/network_manager/event_catcher.rb
  app/models/manageiq/providers/amazon/network_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/amazon/network_manager/refresh_worker.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_worker.rb
  app/models/manageiq/providers/amazon/storage_manager/s3/refresh_worker.rb
  spec/models/manageiq/providers/amazon/agent_coordinator_worker_spec.rb
Labels: refactoring

#577 Remove unused sub-manager refresh workers
  app/models/manageiq/providers/amazon/network_manager/refresh_worker.rb
  app/models/manageiq/providers/amazon/network_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_worker.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_worker/runner.rb
Labels: technical debt

#578 Remove the require_nested calls for removed refresh workers
  app/models/manageiq/providers/amazon/network_manager.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs.rb
Labels: bug
