Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2019-03, with the labels that each got.

#518 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#519 Remove references to MiqPassword
  app/models/manageiq/providers/amazon/manager_mixin.rb
  spec/models/authenticator/amazon_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
Labels: technical debt

#520 Update supported ruby versions on Travis
  .travis.yml
Labels: test

#521 [Changelog] Update for Hammer-4
  CHANGELOG.md
Labels: documentation, hammer/yes
