Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2019-05, with the labels that each got.

#534 Change plugin common methods to class methods
  lib/manageiq/providers/amazon/engine.rb
Labels: refactoring

#535 undisable all regions
  config/settings.yml
Labels: enhancement

#536 [Changelog] Update for Hammer-6
  CHANGELOG.md
Labels: documentation

#537 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test
