Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2019-02, with the labels that each got.

#513 Removal of static attributes in factories
  spec/factories/cloud_volume.rb
  spec/factories/ext_management_system.rb
  spec/factories/orchestration_template.rb
Labels: refactoring, test

#514 update instance types and regions
  db/fixtures/aws_instance_types.yml
  db/fixtures/aws_regions.yml
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
  spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
  spec/models/manageiq/providers/amazon/regions_spec.rb
  spec/vcr_cassettes/manageiq/providers/amazon/regions.yml
Labels: hammer/yes

#515 Add checking on route before retrieving its gateway_id
  app/models/manageiq/providers/amazon/agent_coordinator.rb
Labels: bug, smart state

#516 Remove old ManagerRefresher class
  app/models/manageiq/providers/amazon/cloud_manager/refresher.rb
  app/models/manageiq/providers/amazon/network_manager/refresher.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs/refresher.rb
  app/models/manageiq/providers/amazon/storage_manager/s3/refresher.rb
Labels: cleanup

#517 Return true for memory_mb_available?
  app/models/manageiq/providers/amazon/cloud_manager/vm.rb
Labels: bug
