Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2020-10, with the labels that each got.

#656 Queue name for ems no longer an array
  spec/models/manageiq/providers/amazon/cloud_manager/refresh_worker_spec.rb
Labels: cleanup, test

#655 [JANSA] Update the amazon smartstate docker image
  config/settings.yml
Labels: bug

#659 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#658 Add fields for smartstate docker credentials into the provider form
  app/models/manageiq/providers/amazon/cloud_manager.rb
Labels: bug

#660 Fix the service_instance#extra matcher
  spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Labels: test

#661 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#662 [KASPAROV] Update amazon-smartstate container image for kasparov branch
  config/settings.yml
Labels: bug
