Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2020-02, with the labels that each got.

#580 Add a method to create an AWS EMS from DDF params
  app/models/manageiq/providers/amazon/cloud_manager.rb
  app/models/manageiq/providers/amazon/manager_mixin.rb
Labels: enhancement

#588 Fix verify_credentials always returning true
  app/models/manageiq/providers/amazon/manager_mixin.rb
Labels: bug

#590 Require aws-sdk-core in aws spec helper
  spec/models/manageiq/providers/amazon/aws_helper.rb
Labels: bug, bug/sporadic test failure, test

#593 Delay load ssa support
  app/models/manageiq/providers/amazon/agent_coordinator.rb
  app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb
Labels: performance

#595 Create ems.endpoints when using create_from_params
  app/models/manageiq/providers/amazon/cloud_manager.rb
  spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream_spec.rb
Labels: bug

#598 Retrieve the password from the DB when validating an existing EMS
  app/models/manageiq/providers/amazon/manager_mixin.rb
Labels: enhancement

#600 Fix an uninitialized constant Aws::CloudFormation
  spec/models/manageiq/providers/amazon/cloud_manager/orchestration_stack_spec.rb
Labels: bug, bug/sporadic test failure, test

#601 Fall back with default endpoint in DDF if nothing comes from the API
  app/models/manageiq/providers/amazon/cloud_manager.rb
Labels: bug
