Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2020-09, with the labels that each got.

#646 Remove executable bit from files that don't need it
  CHANGELOG.md
Labels: bug

#647 Fix bug where new regions are not reflected in the list
  app/models/manageiq/providers/amazon/cloud_manager.rb
  spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
Labels: bug, jansa/yes?

#648 Prefer to not memoize at all for dynamic params
  app/models/manageiq/providers/amazon/cloud_manager.rb
  spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
Labels: cleanup, jansa/yes?

#650 Use the tag_mapper from the core Persister
  app/models/manageiq/providers/amazon/inventory/persister.rb
Labels: refactoring

#651 Rename ContainerLabelTagMapping to be more general
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
Labels: refactoring

#652 Keep the parent manager's tenant_id in sync with its child managers
  app/models/manageiq/providers/amazon/cloud_manager.rb
Labels: bug

#654 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/amazon/manager_mixin.rb
Labels: enhancement
