Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2020-03, with the labels that each got.

#602 Fix metrics_capture_spec vcr cassettes
  spec/models/manageiq/providers/amazon/cloud_manager/metrics_capture_spec.rb
Labels: test

#603 Remove invalid partials in Amazon specs
  spec/models/manageiq/providers/amazon/aws_stubs.rb
Labels: refactoring, test

#605 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#606 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#608 remove inventory object refresh
  app/models/manageiq/providers/amazon/cloud_manager.rb
  app/models/manageiq/providers/amazon/network_manager.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs.rb
  app/models/manageiq/providers/amazon/storage_manager/s3.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
  spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
Labels: cleanup

#610 Force pagination of results for V3 library
  app/models/manageiq/providers/amazon/agent_coordinator.rb
  app/models/manageiq/providers/amazon/cloud_manager/metrics_capture.rb
  app/models/manageiq/providers/amazon/inventory/collector.rb
  app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/collector/network_manager.rb
  app/models/manageiq/providers/amazon/inventory/collector/storage_manager/ebs.rb
  app/models/manageiq/providers/amazon/inventory/collector/storage_manager/s3.rb
  app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
Labels: bug

#611 Remove unused ems_inv_to_hashes method
  app/models/manageiq/providers/amazon/parser_helper_methods.rb
  app/models/manageiq/providers/amazon/refresh_helper_methods.rb
Labels: cleanup

#612 Fix cloud manager refresher spec described class name
  spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Labels: technical debt, test
