Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2020-07, with the labels that each got.

#634 Remove unused workers and worker config
  app/models/manageiq/providers/amazon/network_manager/event_catcher.rb
  app/models/manageiq/providers/amazon/network_manager/metrics_collector_worker.rb
  config/settings.yml
Labels: technical debt

#639 Update volume_id fetching for volume modification events
  app/models/manageiq/providers/amazon/cloud_manager/event_target_parser.rb
  spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/AWS_API_CALL_ModifyVolume.json
  spec/models/manageiq/providers/amazon/cloud_manager/event_target_parser_spec.rb
Labels: bug

#641 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement

#640 Rename the key_pairs collection
  app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
Labels: refactoring
