Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2020-05, with the labels that each got.

#622 Adjusted DDF schema and removed create/edit methods
  app/models/manageiq/providers/amazon/cloud_manager.rb
Labels: refactoring

#623 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#624 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#626 Add supports terminate feature
  app/models/manageiq/providers/amazon/cloud_manager/vm/operations.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb
Labels: bug, jansa/yes?
