Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2020-04, with the labels that each got.

#617 Use symbols instead of strings for accessing secrets
  spec/factories/ext_management_system.rb
Labels: bug, test

#613 Updates for Sprint 133
  CHANGELOG.md
Labels: documentation

#618 Update Floating IP target and event collection
  app/models/manageiq/providers/amazon/cloud_manager/event_target_parser.rb
  app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/amazon/cloud_manager/event_target_parser_spec.rb
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/ec2_classic_vm_and_lb_full_refresh.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested_with_vm.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_floating_ip_and_lbs_full_refresh.yml
  spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_public_ip_and_template.yml
Labels: bug
