Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2021-12, with the labels that each got.

#730 Fix regions spec after rename to from_source
  spec/models/manageiq/providers/amazon/regions_spec.rb
Labels: bug, test

#731 renaming supports :ems_network_new to update
  app/models/manageiq/providers/amazon/cloud_manager.rb
  app/models/manageiq/providers/amazon/container_manager.rb
  app/models/manageiq/providers/amazon/network_manager.rb
  spec/models/manageiq/providers/amazon/network_manager_spec.rb
Labels: refactoring

#733 Bump full_refresh_threshold for aws max filter size test
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
Labels: test
