Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2021-04, with the labels that each got.

#692 Use pluggable provider secrets for vcr specs
  config/secrets.defaults.yml
  lib/manageiq/providers/amazon/engine.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/amazon/container_manager/refresher_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/amazon/container_manager/refresher.yml
Labels: refactoring, test

#695 Use Vmdb::Utils.http_proxy_uri when adding AWS provider
  app/models/manageiq/providers/amazon/manager_mixin.rb
Labels: bug, lasker/yes?

#696 Add CloudVolume supports update
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Labels: technical debt

#697 Added Number Value Validator to Form Schema
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Labels: bug

#698 Remove unused validate_update_volume
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Labels: technical debt

#700 Don't normalize_os_name if image_location is nil
  app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
Labels: bug, kasparov/yes?, lasker/yes?

#702 [KASPAROV] Replace authentication_status_ok? with provider specific version
  app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
Labels: performance
