Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2021-02, with the labels that each got.

#679 Add a basic container manager for Amazon EKS
  app/models/manageiq/providers/amazon/container_manager.rb
  app/models/manageiq/providers/amazon/container_manager/container.rb
  app/models/manageiq/providers/amazon/container_manager/container_group.rb
  app/models/manageiq/providers/amazon/container_manager/container_node.rb
  app/models/manageiq/providers/amazon/container_manager/event_catcher.rb
  app/models/manageiq/providers/amazon/container_manager/event_catcher/runner.rb
  app/models/manageiq/providers/amazon/container_manager/event_parser.rb
  app/models/manageiq/providers/amazon/container_manager/refresh_worker.rb
  app/models/manageiq/providers/amazon/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/amazon/container_manager/refresher.rb
  app/models/manageiq/providers/amazon/inventory/collector.rb
  app/models/manageiq/providers/amazon/inventory/collector/container_manager.rb
  app/models/manageiq/providers/amazon/inventory/parser.rb
  app/models/manageiq/providers/amazon/inventory/parser/container_manager.rb
  app/models/manageiq/providers/amazon/inventory/persister.rb
  app/models/manageiq/providers/amazon/inventory/persister/container_manager.rb
  config/settings.yml
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/amazon/container_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/amazon/container_manager/refresher.yml
Labels: enhancement

#681 Fixed the creation of CloudVolumes via API/DDF
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
  spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_spec.rb
Labels: bug

#680 Add WatchNotice subclasses and enable streaming refresh
  app/models/manageiq/providers/amazon/container_manager/refresh_worker.rb
  app/models/manageiq/providers/amazon/container_manager/refresh_worker/watch_thread.rb
  app/models/manageiq/providers/amazon/inventory/collector/container_manager.rb
  app/models/manageiq/providers/amazon/inventory/collector/container_manager/watch_notice.rb
  app/models/manageiq/providers/amazon/inventory/parser/container_manager.rb
  app/models/manageiq/providers/amazon/inventory/parser/container_manager/watch_notice.rb
  app/models/manageiq/providers/amazon/inventory/persister/container_manager.rb
  app/models/manageiq/providers/amazon/inventory/persister/container_manager/watch_notice.rb
  config/settings.yml
Labels: enhancement

#683 Fix EKS scheduled auth check returning missing creds
  app/models/manageiq/providers/amazon/container_manager.rb
  spec/models/manageiq/providers/amazon/container_manager/refresher_spec.rb
Labels: bug

#685 Adjust empty/initial values for select fields in DDF schemas
  app/models/manageiq/providers/amazon/cloud_manager.rb
  app/models/manageiq/providers/amazon/container_manager.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Labels: enhancement

#686 Fix AgentCoordinatorWorker sync_workers
  app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
  spec/models/manageiq/providers/amazon/agent_coordinator_worker_spec.rb
Labels: bug, jansa/yes?, kasparov/yes?

#687 Refactor AgentCoordinatorWorker to use ProviderWorkerMixin
  app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
Labels: refactoring

#684 Parse flavors from the collector not the persister
  app/models/manageiq/providers/amazon/instance_types.rb
  app/models/manageiq/providers/amazon/inventory/collector.rb
  app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
  app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
Labels: bug
