Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2021-05, with the labels that each got.

#701 Subclassed provider classes should mark the parent as a leaf class
  app/models/manageiq/providers/amazon/container_manager.rb
  app/models/manageiq/providers/amazon/container_manager/container.rb
  app/models/manageiq/providers/amazon/container_manager/container_group.rb
  app/models/manageiq/providers/amazon/container_manager/container_node.rb
Labels: refactoring

#705 Add supports :metrics to Amazon CloudManager
  app/models/manageiq/providers/amazon/cloud_manager.rb
Labels: enhancement

#704 Use targeted persister strategy from core
  app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb
Labels: enhancement

#703 Move to Block/ObjectStorageManager for EBS/S3
  app/models/manageiq/providers/amazon/storage_manager/ebs.rb
  app/models/manageiq/providers/amazon/storage_manager/s3.rb
Labels: refactoring

#707 Add back an instance_types rake task
  db/fixtures/aws_instance_types.yml
  lib/tasks_private/instance_types.rake
Labels: bug
