Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2021-09, with the labels that each got.

#719 Convert cloud volume operations to SupportsFeatureMixin
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Labels: technical debt

#723 Fix labeled_resource_type for Amazon Vms/Images
  app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
Labels: bug, morphy/yes?

#724 Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
  .travis.yml
Labels: test
