Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2021-03, with the labels that each got.

#688 Don't override add_miq_templates to set the model_class
  app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
Labels: refactoring

#689 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#678 Add systemd unit files for workers
  app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
  build/systemd_units/manageiq-providers-amazon_agent_coordinator.target
  build/systemd_units/manageiq-providers-amazon_agent_coordinator@.service
  build/systemd_units/manageiq-providers-amazon_cloud_manager_event_catcher.target
  build/systemd_units/manageiq-providers-amazon_cloud_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-amazon_cloud_manager_metrics_collector.target
  build/systemd_units/manageiq-providers-amazon_cloud_manager_metrics_collector@.service
  build/systemd_units/manageiq-providers-amazon_cloud_manager_refresh.target
  build/systemd_units/manageiq-providers-amazon_cloud_manager_refresh@.service
  build/systemd_units/manageiq-providers-amazon_storage_manager_s3_refresh.target
  build/systemd_units/manageiq-providers-amazon_storage_manager_s3_refresh@.service
Labels: technical debt
