Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2021-08, with the labels that each got.

#716 Move endpoint notice filtering into base class
  app/models/manageiq/providers/amazon/container_manager/refresh_worker/watch_thread.rb
Labels: refactoring

#717 Add supports :storage_manager and block_storage_manager Function to Amazon CloudManager
  app/models/manageiq/providers/amazon/cloud_manager.rb
Labels: enhancement

#718 Prevent services other than EC2 from causing refresh failures
  app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/collector/network_manager.rb
Labels: bug

#720 Add branch release tasks
  lib/tasks_private/release.rake
Labels: enhancement, tools, morphy/yes?
