Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2022-03, with the labels that each got.

#747 Fix stack template errors causing [].encode exception
  app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
Labels: bug, najdorf/yes?

#746 Refactor AuthKeyPair.raw_create_key_pair
  app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Labels: refactoring

#749 Fix gettext interpolation syntax in unsupported_reason_add
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Labels: bug, najdorf/yes?

#750 Fix auth_key_pair create params
  app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Labels: bug, najdorf/yes?

#748 Update AWS instance types list
  db/fixtures/aws_instance_types.yml
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
  spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
Labels: enhancement

#754 Add support for creating cloud object store containers
  app/models/manageiq/providers/amazon/storage_manager/s3.rb
  app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
Labels: refactoring
