Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2022-05, with the labels that each got.

#768 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#767 rename CloudVolume#attach_volume to attach
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Labels: enhancement

#770 Cleanup duplicated supports_authentication? methods
  app/models/manageiq/providers/amazon/cloud_manager.rb
Labels: technical debt
