Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2022-04, with the labels that each got.

#753 Added fields for create cloud object store container form and support for create
  app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
Labels: enhancement

#755 Cloud volume snapshot
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot.rb
Labels: enhancement

#757 Create cloud databases support
  app/models/manageiq/providers/amazon/cloud_manager/cloud_database.rb
  spec/factories/cloud_database.rb
  spec/models/manageiq/providers/amazon/cloud_manager/cloud_database_spec.rb
Labels: enhancement

#758 Delete cloud database support
  app/models/manageiq/providers/amazon/cloud_manager/cloud_database.rb
  spec/models/manageiq/providers/amazon/cloud_manager/cloud_database_spec.rb
Labels: enhancement

#752 Add github action to update instance-types
  .github/workflows/instance_types.yaml
  .gitignore
Labels: developer

#765 Dynamically check flavors count from aws_instance_types.yml
  spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
  spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
  spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Labels: enhancement, test
