Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2022-02, with the labels that each got.

#738 [MORPHY] Fix network_manager zone_before_pause
  app/models/manageiq/providers/amazon/cloud_manager.rb
Labels: wip

#740 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/ci/after_script
  manageiq-providers-amazon.gemspec
Labels: test

#742 Fix bin/setup and bundler conflict
  .github/workflows/ci.yaml
  bin/before_install
  bin/setup
Labels: test, developer

#743 Add Build History Graph to README.md
  README.md
Labels: test, developer

#741 Fixed the cloud volume add/edit form
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Labels: bug

#745 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: test, developer
