Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2023-10, with the labels that each got.

#828 Add ContainerManager #pause! and #resume! specs
  spec/models/manageiq/providers/amazon/container_manager_spec.rb
Labels: test

#831 Update AWS regions.yml
  config/regions.yml
  lib/tasks_private/regions.rake
  spec/models/manageiq/providers/amazon/regions_spec.rb
  spec/vcr_cassettes/manageiq/providers/amazon/regions.yml
Labels: enhancement, petrosian/yes?, quinteros/yes?

#836 Drop Ruby 2.7
  .github/workflows/ci.yaml
Labels: dependencies
