Repository ManageIQ/manageiq-providers-amazon, pull requests merged in 2024-02, with the labels that each got.

#839 Bump Ruby version for instance_types GitHub action
  .github/workflows/instance_types.yaml
Labels: developer

#841 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#845 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1

#843 Drop supports_feature? and unsupported_reason_add
  app/models/manageiq/providers/amazon/cloud_manager/template.rb
  app/models/manageiq/providers/amazon/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/amazon/cloud_manager/vm/operations/guest.rb
  app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb
  app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
  app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
  app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_object.rb
  spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb
Labels: refactoring, radjabov/yes?
